import type { ModuleEntryMetric, RepoQuoteSection } from "../../types";
import type { AmountFilterUnit } from "./quoteBoard.types";

export const repoQuoteSections: readonly RepoQuoteSection[] = [
  {
    id: "reverse",
    title: "逆回购",
    groups: [
      {
        id: "reverse-rate-local",
        name: "利率地方",
        tenorSummary: "R001 / R007 / R014",
        totalAmount: "25亿",
        averageRate: "1.40%",
        collateral: "利率债 / 地方债",
        badges: ["R001 最优", "R007 次优", "R014 最优"],
        rows: [
          {
            id: "reverse-rate-local-citic",
            institution: "中信银行",
            tenor: "R001",
            amount: "10亿",
            rate: "1.35%",
            collateral: "利率",
            rank: "最优",
            reason: "这是 R001 最优",
            accountType: "自营户",
            minimum: "5亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-rate-local-bj",
            institution: "北京银行",
            tenor: "R007",
            amount: "5亿",
            rate: "1.40%",
            collateral: "利率地方存单商金",
            rank: "最优",
            reason: "这是 R007 最优",
            accountType: "商金户",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-rate-local-shrcb",
            institution: "上海农商行",
            tenor: "R001",
            amount: "10亿",
            rate: "1.41%",
            collateral: "利率",
            rank: "次优",
            reason: "R001 次优",
            accountType: "商金户",
            minimum: "5亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-rate-local-gz",
            institution: "广州银行",
            tenor: "R014",
            amount: "6亿",
            rate: "1.43%",
            collateral: "利率地方存单商金",
            rank: "最优",
            reason: "这是 R014 最优",
            accountType: "自营户",
            minimum: "3亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-rate-local-cmb",
            institution: "招商银行",
            tenor: "R001",
            amount: "8亿",
            rate: "1.42%",
            collateral: "利率",
            rank: "报价",
            reason: "R001 一般报价",
            accountType: "股份行自营",
            minimum: "3亿起",
            updatedAt: "10:53:18",
          },
          {
            id: "reverse-rate-local-spdb",
            institution: "浦发银行",
            tenor: "R007",
            amount: "4亿",
            rate: "1.43%",
            collateral: "地方债",
            rank: "次优",
            reason: "R007 次优",
            accountType: "股份行自营",
            minimum: "2亿起",
            updatedAt: "10:53:14",
          },
          {
            id: "reverse-rate-local-cmbc",
            institution: "民生银行",
            tenor: "R001",
            amount: "3亿",
            rate: "1.44%",
            collateral: "利率",
            rank: "报价",
            reason: "R001 一般报价",
            accountType: "股份行自营",
            minimum: "1亿起",
            updatedAt: "10:53:08",
          },
          {
            id: "reverse-rate-local-zhrcb",
            institution: "珠海农商行",
            tenor: "R007",
            amount: "2亿",
            rate: "1.45%",
            collateral: "利率地方",
            rank: "报价",
            reason: "R007 一般报价",
            accountType: "商金户",
            minimum: "1亿起",
            updatedAt: "10:52:55",
          },
          {
            id: "reverse-rate-local-cqrcb",
            institution: "重庆农商行",
            tenor: "R014",
            amount: "3亿",
            rate: "1.46%",
            collateral: "地方债",
            rank: "报价",
            reason: "R014 一般报价",
            accountType: "商金户",
            minimum: "1亿起",
            updatedAt: "10:52:42",
          },
        ],
      },
      {
        id: "reverse-cd-sj",
        name: "存单商金",
        tenorSummary: "R001 / R007",
        totalAmount: "7亿",
        averageRate: "1.41%",
        collateral: "大行存单 / 商金",
        badges: ["R001 最优", "R007 次优"],
        rows: [
          {
            id: "reverse-cd-sj-bj",
            institution: "北京银行",
            tenor: "R001",
            amount: "5亿",
            rate: "1.40%",
            collateral: "利率地方存单商金",
            rank: "最优",
            reason: "这是 R001 最优",
            accountType: "商金户",
            minimum: "5亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-cd-sj-nongyin",
            institution: "农银理财",
            tenor: "R007",
            amount: "2亿",
            rate: "1.42%",
            collateral: "大行存单",
            rank: "最优",
            reason: "这是 R007 最优",
            accountType: "理财子",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-cd-sj-yangguang",
            institution: "阳光资产",
            tenor: "R007",
            amount: "5亿",
            rate: "1.40%",
            collateral: "利率地方存单商金",
            rank: "次优",
            reason: "R007 次优",
            accountType: "保险资管",
            minimum: "3亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-cd-sj-cmbwm",
            institution: "招银理财",
            tenor: "R001",
            amount: "3亿",
            rate: "1.41%",
            collateral: "大行存单",
            rank: "报价",
            reason: "R001 一般报价",
            accountType: "理财子",
            minimum: "1亿起",
            updatedAt: "10:53:21",
          },
          {
            id: "reverse-cd-sj-icbcwm",
            institution: "工银理财",
            tenor: "R007",
            amount: "4亿",
            rate: "1.43%",
            collateral: "商金存单",
            rank: "报价",
            reason: "R007 一般报价",
            accountType: "理财子",
            minimum: "2亿起",
            updatedAt: "10:53:11",
          },
          {
            id: "reverse-cd-sj-taikang",
            institution: "太保资产",
            tenor: "R001",
            amount: "5亿",
            rate: "1.42%",
            collateral: "国股存单",
            rank: "次优",
            reason: "R001 次优",
            accountType: "保险资管",
            minimum: "3亿起",
            updatedAt: "10:53:04",
          },
          {
            id: "reverse-cd-sj-bocomwm",
            institution: "交银理财",
            tenor: "R007",
            amount: "2亿",
            rate: "1.44%",
            collateral: "商金存单",
            rank: "报价",
            reason: "R007 一般报价",
            accountType: "理财子",
            minimum: "1亿起",
            updatedAt: "10:52:48",
          },
        ],
      },
      {
        id: "reverse-credit",
        name: "信用",
        tenorSummary: "R001 / R007 / R014",
        totalAmount: "12.45亿",
        averageRate: "1.44%",
        collateral: "信用债 / 年金户",
        badges: ["R001 最优", "R007 最优", "R014 最优"],
        rows: [
          {
            id: "reverse-credit-penghua",
            institution: "鹏华基金",
            tenor: "R007",
            amount: "4亿",
            rate: "1.45%",
            collateral: "AAA",
            rank: "最优",
            reason: "这是 R007 最优",
            accountType: "公募基金",
            minimum: "1亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-credit-pingan",
            institution: "平安资产",
            tenor: "R001",
            amount: "10亿",
            rate: "1.43%",
            collateral: "单笔 1e 起",
            rank: "次优",
            reason: "R001 次优",
            accountType: "保险资管",
            minimum: "单笔 1e 起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-credit-cncbsec",
            institution: "中信建投证券",
            tenor: "R001",
            amount: "2.45亿",
            rate: "1.43%",
            collateral: "年金户",
            rank: "最优",
            reason: "这是 R001 最优",
            accountType: "券商自营",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-credit-huaan",
            institution: "华安基金",
            tenor: "R014",
            amount: "3亿",
            rate: "1.45%",
            collateral: "AAA",
            rank: "最优",
            reason: "这是 R014 最优",
            accountType: "公募基金",
            minimum: "1亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "reverse-credit-citicsec",
            institution: "中信证券",
            tenor: "R007",
            amount: "5亿",
            rate: "1.46%",
            collateral: "AA+",
            rank: "次优",
            reason: "R007 次优",
            accountType: "券商自营",
            minimum: "2亿起",
            updatedAt: "10:53:19",
          },
          {
            id: "reverse-credit-eastspring",
            institution: "东方红资产",
            tenor: "R014",
            amount: "2亿",
            rate: "1.47%",
            collateral: "年金户",
            rank: "次优",
            reason: "R014 次优",
            accountType: "券商资管",
            minimum: "1亿起",
            updatedAt: "10:53:09",
          },
          {
            id: "reverse-credit-bosc",
            institution: "上海银行",
            tenor: "R001",
            amount: "4亿",
            rate: "1.46%",
            collateral: "AA+",
            rank: "报价",
            reason: "R001 一般报价",
            accountType: "城商行自营",
            minimum: "2亿起",
            updatedAt: "10:52:58",
          },
          {
            id: "reverse-credit-gtja",
            institution: "国泰君安",
            tenor: "R007",
            amount: "3亿",
            rate: "1.48%",
            collateral: "AA+",
            rank: "报价",
            reason: "R007 一般报价",
            accountType: "券商自营",
            minimum: "1亿起",
            updatedAt: "10:52:46",
          },
          {
            id: "reverse-credit-hsfund",
            institution: "华夏基金",
            tenor: "R014",
            amount: "2亿",
            rate: "1.49%",
            collateral: "AAA",
            rank: "报价",
            reason: "R014 一般报价",
            accountType: "公募基金",
            minimum: "1亿起",
            updatedAt: "10:52:31",
          },
        ],
      },
    ],
  },
  {
    id: "forward",
    title: "正回购",
    groups: [
      {
        id: "forward-rate-local",
        name: "利率地方",
        tenorSummary: "R001 / R007 / R014",
        totalAmount: "18亿",
        averageRate: "1.52%",
        collateral: "利率债 / 地方债",
        badges: ["R001 最优", "R007 最优", "R014 次优"],
        rows: [
          {
            id: "forward-rate-local-boc",
            institution: "中国银行",
            tenor: "R001",
            amount: "8亿",
            rate: "1.51%",
            collateral: "利率",
            rank: "最优",
            reason: "这是 R001 最优",
            accountType: "大行自营",
            minimum: "5亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-rate-local-ccb",
            institution: "建设银行",
            tenor: "R007",
            amount: "6亿",
            rate: "1.53%",
            collateral: "利率地方",
            rank: "最优",
            reason: "这是 R007 最优",
            accountType: "大行自营",
            minimum: "3亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-rate-local-jt",
            institution: "交通银行",
            tenor: "R014",
            amount: "4亿",
            rate: "1.54%",
            collateral: "利率地方",
            rank: "次优",
            reason: "R014 次优",
            accountType: "股份行",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-rate-local-abc",
            institution: "农业银行",
            tenor: "R001",
            amount: "6亿",
            rate: "1.52%",
            collateral: "利率",
            rank: "次优",
            reason: "R001 次优",
            accountType: "大行自营",
            minimum: "3亿起",
            updatedAt: "10:53:18",
          },
          {
            id: "forward-rate-local-icbc",
            institution: "工商银行",
            tenor: "R007",
            amount: "5亿",
            rate: "1.54%",
            collateral: "利率",
            rank: "次优",
            reason: "R007 次优",
            accountType: "大行自营",
            minimum: "3亿起",
            updatedAt: "10:53:09",
          },
          {
            id: "forward-rate-local-cmbc",
            institution: "民生银行",
            tenor: "R001",
            amount: "3亿",
            rate: "1.53%",
            collateral: "利率地方",
            rank: "报价",
            reason: "R001 一般报价",
            accountType: "股份行",
            minimum: "2亿起",
            updatedAt: "10:52:58",
          },
          {
            id: "forward-rate-local-cib",
            institution: "兴业银行",
            tenor: "R014",
            amount: "2亿",
            rate: "1.55%",
            collateral: "地方债",
            rank: "报价",
            reason: "R014 一般报价",
            accountType: "股份行",
            minimum: "1亿起",
            updatedAt: "10:52:43",
          },
        ],
      },
      {
        id: "forward-cd-sj",
        name: "存单商金",
        tenorSummary: "R001 / R007",
        totalAmount: "9亿",
        averageRate: "1.57%",
        collateral: "国股存单 / 商金",
        badges: ["R001 次优", "R007 最优"],
        rows: [
          {
            id: "forward-cd-sj-cmbwm",
            institution: "招银理财",
            tenor: "R007",
            amount: "4亿",
            rate: "1.58%",
            collateral: "国股存单",
            rank: "最优",
            reason: "这是 R007 最优",
            accountType: "理财子",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-cd-sj-icbcwm",
            institution: "工银理财",
            tenor: "R001",
            amount: "3亿",
            rate: "1.56%",
            collateral: "商金存单",
            rank: "次优",
            reason: "R001 次优",
            accountType: "理财子",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-cd-sj-bjrcb",
            institution: "北京农商行",
            tenor: "R007",
            amount: "2亿",
            rate: "1.59%",
            collateral: "商金存单",
            rank: "次优",
            reason: "R007 次优",
            accountType: "商金户",
            minimum: "1亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-cd-sj-ccbwm",
            institution: "建信理财",
            tenor: "R001",
            amount: "4亿",
            rate: "1.57%",
            collateral: "国股存单",
            rank: "最优",
            reason: "这是 R001 最优",
            accountType: "理财子",
            minimum: "2亿起",
            updatedAt: "10:53:14",
          },
          {
            id: "forward-cd-sj-bocwm",
            institution: "中银理财",
            tenor: "R007",
            amount: "3亿",
            rate: "1.60%",
            collateral: "商金存单",
            rank: "报价",
            reason: "R007 一般报价",
            accountType: "理财子",
            minimum: "2亿起",
            updatedAt: "10:53:01",
          },
          {
            id: "forward-cd-sj-shrcb",
            institution: "上海农商行",
            tenor: "R001",
            amount: "2亿",
            rate: "1.58%",
            collateral: "国股存单",
            rank: "报价",
            reason: "R001 一般报价",
            accountType: "商金户",
            minimum: "1亿起",
            updatedAt: "10:52:46",
          },
        ],
      },
      {
        id: "forward-credit",
        name: "信用",
        tenorSummary: "R001 / R007 / R021",
        totalAmount: "13.2亿",
        averageRate: "1.61%",
        collateral: "信用债 / 专户 / 年金",
        badges: ["R001 最优", "R007 次优", "R021 最优"],
        rows: [
          {
            id: "forward-credit-citicsec",
            institution: "中信证券",
            tenor: "R001",
            amount: "5亿",
            rate: "1.60%",
            collateral: "AA+",
            rank: "最优",
            reason: "这是 R001 最优",
            accountType: "券商自营",
            minimum: "1亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-credit-pinganam",
            institution: "平安资管",
            tenor: "R007",
            amount: "3.2亿",
            rate: "1.62%",
            collateral: "信用债专户",
            rank: "次优",
            reason: "R007 次优",
            accountType: "保险资管",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-credit-eastspring",
            institution: "东方红资产",
            tenor: "R021",
            amount: "5亿",
            rate: "1.63%",
            collateral: "年金户",
            rank: "最优",
            reason: "这是 R021 最优",
            accountType: "券商资管",
            minimum: "2亿起",
            updatedAt: "10:53:27",
          },
          {
            id: "forward-credit-bofcom",
            institution: "交银施罗德",
            tenor: "R001",
            amount: "3亿",
            rate: "1.61%",
            collateral: "AAA",
            rank: "次优",
            reason: "R001 次优",
            accountType: "公募基金",
            minimum: "1亿起",
            updatedAt: "10:53:13",
          },
          {
            id: "forward-credit-cmbsec",
            institution: "招商证券",
            tenor: "R007",
            amount: "4亿",
            rate: "1.63%",
            collateral: "信用债",
            rank: "报价",
            reason: "R007 一般报价",
            accountType: "券商自营",
            minimum: "2亿起",
            updatedAt: "10:53:02",
          },
          {
            id: "forward-credit-pinganfund",
            institution: "平安基金",
            tenor: "R021",
            amount: "2亿",
            rate: "1.64%",
            collateral: "年金户",
            rank: "次优",
            reason: "R021 次优",
            accountType: "公募基金",
            minimum: "1亿起",
            updatedAt: "10:52:51",
          },
          {
            id: "forward-credit-cinda",
            institution: "信达证券",
            tenor: "R001",
            amount: "2亿",
            rate: "1.62%",
            collateral: "AA+",
            rank: "报价",
            reason: "R001 一般报价",
            accountType: "券商自营",
            minimum: "1亿起",
            updatedAt: "10:52:38",
          },
          {
            id: "forward-credit-htsec",
            institution: "海通证券",
            tenor: "R007",
            amount: "3亿",
            rate: "1.65%",
            collateral: "AA+",
            rank: "报价",
            reason: "R007 一般报价",
            accountType: "券商自营",
            minimum: "2亿起",
            updatedAt: "10:52:24",
          },
        ],
      },
    ],
  },
] as const;

export const topBoardFilters = {
  periods: ["全部", "1", "7", "14", "21", "28+"],
  amountMin: "0",
  amountMax: "不限",
  rateMin: "0.00",
  rateMax: "不限",
} as const;

export const quoteBoardGlobalFilterMetric: ModuleEntryMetric = {
  summary: `金额 ${topBoardFilters.amountMin}-${topBoardFilters.amountMax}亿 · 利率 ${topBoardFilters.rateMin}-${topBoardFilters.rateMax}%`,
  badge: "筛选",
  rows: [
    ["金额", `${topBoardFilters.amountMin} - ${topBoardFilters.amountMax}亿`],
    ["利率", `${topBoardFilters.rateMin} - ${topBoardFilters.rateMax}%`],
  ],
  chips: [
    { label: "金额", value: `${topBoardFilters.amountMin}-${topBoardFilters.amountMax}`, tone: "muted" },
    { label: "利率", value: `${topBoardFilters.rateMin}-${topBoardFilters.rateMax}`, tone: "muted" },
  ],
  detailRows: [
    ["金额范围", `${topBoardFilters.amountMin}-${topBoardFilters.amountMax}亿`, "已应用"],
    ["利率范围", `${topBoardFilters.rateMin}-${topBoardFilters.rateMax}%`, "已应用"],
  ],
};

export const quoteContactNames: Record<string, string> = {
  中信银行: "李明轩",
  北京银行: "王知夏",
  上海农商行: "陈以宁",
  广州银行: "周叙白",
  招商银行: "赵予安",
  浦发银行: "刘星野",
  民生银行: "孙若川",
  珠海农商行: "黄景川",
  重庆农商行: "吴书言",
  农银理财: "李见山",
  阳光资产: "许知远",
  招银理财: "周临风",
  工银理财: "张屿川",
  太保资产: "陈北辰",
  交银理财: "赵清和",
  鹏华基金: "林疏桐",
  平安资产: "何沐言",
  中信建投证券: "张砚秋",
  华安基金: "郑知微",
  中信证券: "陆时安",
  东方红资产: "宋景行",
  上海银行: "顾言舟",
  国泰君安: "沈之恒",
  华夏基金: "马清越",
  中国银行: "李承泽",
  建设银行: "孙知行",
  交通银行: "赵元恺",
  农业银行: "李予川",
  工商银行: "张闻野",
  兴业银行: "王牧之",
  北京农商行: "王叙川",
  中银理财: "吴清野",
  平安资管: "何叙安",
  交银施罗德: "赵云澈",
  招商证券: "秦知远",
  平安基金: "何清禾",
  信达证券: "高叙宁",
  海通证券: "唐景川",
};

export const opponentInstitutions = [
  "中信银行",
  "建设银行",
  "农业银行",
  "国泰资产",
  "邮储银行",
  "江苏银行",
  "上海农商",
  "招商基金",
  "平安理财",
  "杭州银行",
  "上海银行",
  "华安基金",
] as const;

export const ACCOUNT_TYPE_OPTIONS = [
  "自营户",
  "商金户",
  "股份行自营",
  "理财子",
  "保险资管",
  "公募基金",
  "券商自营",
  "券商资管",
  "城商行自营",
  "大行自营",
  "股份行",
  "可专户",
  "年金户",
] as const;

export const COLLATERAL_OPTIONS = [
  "利率",
  "利率地方",
  "地方债",
  "利率地方存单商金",
  "大行存单",
  "商金存单",
  "国股存单",
  "大行存单 / 商金",
  "国股存单 / 商金",
  "信用债",
  "AAA",
  "AA+",
] as const;

export const INSTITUTION_FILTER_OPTIONS = Array.from(
  new Set(
    Object.entries(quoteContactNames).flatMap(([institution, sender]) => [
      institution,
      sender,
      `${institution} / ${sender}`,
    ]),
  ),
).sort((left, right) => left.localeCompare(right, "zh-CN"));

export const PINNED_INSTITUTION_FILTER_OPTIONS = ["货币中介"] as const;

export const DEFAULT_AMOUNT_UNIT: AmountFilterUnit = "yi";

export const BROKER_OPTIONS = [
  "国际",
  "国利",
  "平安",
  "中诚",
  "信唐",
  "上田",
] as const;

export const COUNTERPARTY_TAG_OPTIONS = [
  "保险/保障",
  "稳定出钱",
  "出散量",
  "应急",
  "券商自营",
] as const;

export const TAG_COLOR_MAP: Record<string, string> = {
  核心: "#dc2626",
  "保险/保障": "#059669",
  稳定出钱: "#2563eb",
  出散量: "#7c3aed",
  应急: "#d97706",
  券商自营: "#0891b2",
};

export const institutionBrokerMap: Record<string, string> = {
  中信银行: "国际",
  北京银行: "国利",
  上海农商行: "平安",
  广州银行: "中诚",
  招商银行: "国际",
  浦发银行: "信唐",
  民生银行: "上田",
  珠海农商行: "平安",
  重庆农商行: "国利",
  农银理财: "国际",
  阳光资产: "中诚",
  招银理财: "国际",
  工银理财: "国利",
  太保资产: "信唐",
  交银理财: "上田",
  鹏华基金: "平安",
  平安资产: "平安",
  中信建投证券: "国际",
  华安基金: "中诚",
  中信证券: "国际",
  东方红资产: "信唐",
  上海银行: "上田",
  国泰君安: "国利",
  华夏基金: "平安",
  中国银行: "国际",
  建设银行: "国利",
  交通银行: "中诚",
  农业银行: "国际",
  工商银行: "国利",
  兴业银行: "信唐",
  北京农商行: "上田",
  中银理财: "国际",
  平安资管: "平安",
  交银施罗德: "上田",
  招商证券: "国际",
  平安基金: "平安",
  信达证券: "中诚",
  海通证券: "信唐",
};

export const institutionTagsMap: Record<string, readonly string[]> = {
  中信银行: ["稳定出钱"],
  北京银行: ["稳定出钱"],
  上海农商行: ["出散量"],
  广州银行: ["出散量"],
  招商银行: ["稳定出钱"],
  浦发银行: ["稳定出钱"],
  民生银行: ["出散量"],
  珠海农商行: ["出散量"],
  重庆农商行: ["出散量"],
  农银理财: ["稳定出钱"],
  阳光资产: ["保险/保障"],
  招银理财: ["稳定出钱"],
  工银理财: ["稳定出钱"],
  太保资产: ["保险/保障"],
  交银理财: ["稳定出钱"],
  鹏华基金: ["应急"],
  平安资产: ["保险/保障"],
  中信建投证券: ["券商自营"],
  华安基金: ["应急"],
  中信证券: ["券商自营"],
  东方红资产: ["券商自营"],
  上海银行: ["出散量"],
  国泰君安: ["券商自营"],
  华夏基金: ["应急"],
  中国银行: ["稳定出钱"],
  建设银行: ["稳定出钱"],
  交通银行: ["稳定出钱"],
  农业银行: ["稳定出钱"],
  工商银行: ["稳定出钱"],
  兴业银行: ["稳定出钱"],
  北京农商行: ["出散量"],
  中银理财: ["稳定出钱"],
  平安资管: ["保险/保障"],
  交银施罗德: ["应急"],
  招商证券: ["券商自营"],
  平安基金: ["保险/保障", "应急"],
  信达证券: ["券商自营"],
  海通证券: ["券商自营"],
};
