import type { BankRateRow } from "../../types";

export const defaultBigBankWhitelist: readonly string[] = [
  "宸ュ晢閾惰",
  "寤鸿閾惰",
  "鍐滀笟閾惰",
  "涓浗閾惰",
];

export const initialBankRateRows: readonly BankRateRow[] = [
  {
    institution: "宸ュ晢閾惰",
    tenor: "ON",
    nonBankRate: "1.95%",
    refNonBankRate: "1.96%",
    deltaNonBankBp: "-1",
    bankRate: "2.00%",
    refBankRate: "2.00%",
    deltaBp: "0",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "宸ュ晢閾惰",
    tenor: "7D",
    nonBankRate: "2.04%",
    refNonBankRate: "2.04%",
    deltaNonBankBp: "0",
    bankRate: "2.10%",
    refBankRate: "2.12%",
    deltaBp: "-2",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "寤鸿閾惰",
    tenor: "ON",
    nonBankRate: "1.94%",
    refNonBankRate: "1.94%",
    deltaNonBankBp: "0",
    bankRate: "1.99%",
    refBankRate: "2.00%",
    deltaBp: "-1",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "寤鸿閾惰",
    tenor: "7D",
    nonBankRate: "2.06%",
    refNonBankRate: "2.07%",
    deltaNonBankBp: "-1",
    bankRate: "2.11%",
    refBankRate: "2.13%",
    deltaBp: "-2",
    updatedAt: "10:52:54",
    hasQuote: true,
  },
  {
    institution: "鍐滀笟閾惰",
    tenor: "ON",
    nonBankRate: "1.96%",
    refNonBankRate: "1.96%",
    deltaNonBankBp: "0",
    bankRate: "2.01%",
    refBankRate: "2.00%",
    deltaBp: "+1",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "鍐滀笟閾惰",
    tenor: "7D",
    nonBankRate: "2.05%",
    refNonBankRate: "2.06%",
    deltaNonBankBp: "-1",
    bankRate: "2.09%",
    refBankRate: "2.10%",
    deltaBp: "-1",
    updatedAt: "10:52:31",
    hasQuote: true,
  },
  {
    institution: "涓浗閾惰",
    tenor: "ON",
    nonBankRate: "1.93%",
    refNonBankRate: "1.94%",
    deltaNonBankBp: "-1",
    bankRate: "1.98%",
    refBankRate: "2.00%",
    deltaBp: "-2",
    updatedAt: "10:52:12",
    hasQuote: true,
  },
  {
    institution: "涓浗閾惰",
    tenor: "7D",
    nonBankRate: "2.05%",
    refNonBankRate: "2.05%",
    deltaNonBankBp: "0",
    bankRate: "2.10%",
    refBankRate: "2.11%",
    deltaBp: "-1",
    updatedAt: "10:51:58",
    hasQuote: true,
  },
] as const;
