import type { BankRateRow } from "../../types";

export const defaultBigBankWhitelist: readonly string[] = [
  "工商银行",
  "建设银行",
  "农业银行",
  "中国银行",
];

export const initialBankRateRows: readonly BankRateRow[] = [
  {
    institution: "工商银行",
    tenor: "ON",
    nonBankRate: "1.95%",
    refNonBankRate: "1.96%",
    deltaNonBankBp: "",
    bankRate: "2.00%",
    refBankRate: "",
    deltaBp: "",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "工商银行",
    tenor: "7D",
    nonBankRate: "",
    refNonBankRate: "2.04%",
    deltaNonBankBp: "",
    bankRate: "2.10%",
    refBankRate: "2.12%",
    deltaBp: "",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "建设银行",
    tenor: "ON",
    nonBankRate: "1.94%",
    refNonBankRate: "",
    deltaNonBankBp: "",
    bankRate: "",
    refBankRate: "2.00%",
    deltaBp: "",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "建设银行",
    tenor: "7D",
    nonBankRate: "",
    refNonBankRate: "",
    deltaNonBankBp: "",
    bankRate: "",
    refBankRate: "",
    deltaBp: "",
    updatedAt: "",
    hasQuote: false,
  },
  {
    institution: "农业银行",
    tenor: "ON",
    nonBankRate: "",
    refNonBankRate: "1.96%",
    deltaNonBankBp: "",
    bankRate: "2.01%",
    refBankRate: "2.00%",
    deltaBp: "",
    updatedAt: "10:53:27",
    hasQuote: true,
  },
  {
    institution: "农业银行",
    tenor: "7D",
    nonBankRate: "",
    refNonBankRate: "",
    deltaNonBankBp: "",
    bankRate: "",
    refBankRate: "",
    deltaBp: "",
    updatedAt: "",
    hasQuote: false,
  },
  {
    institution: "中国银行",
    tenor: "ON",
    nonBankRate: "",
    refNonBankRate: "1.94%",
    deltaNonBankBp: "",
    bankRate: "",
    refBankRate: "2.00%",
    deltaBp: "",
    updatedAt: "",
    hasQuote: false,
  },
  {
    institution: "中国银行",
    tenor: "7D",
    nonBankRate: "",
    refNonBankRate: "2.05%",
    deltaNonBankBp: "",
    bankRate: "",
    refBankRate: "2.11%",
    deltaBp: "",
    updatedAt: "",
    hasQuote: false,
  },
] as const;
